name: Terraform Infrastructure

on:
  push:
  pull_request:
    
jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    env:
      TF_VAR_render_api_key: ${{ secrets.RENDER_API_KEY }}
      TF_VAR_render_owner_id: ${{ secrets.RENDER_OWNER_ID }}

      TF_VAR_github_repo: ${{ secrets.REPO_URL }}
      TF_VAR_branch: ${{ secrets.BRANCH }}
      TF_VAR_port: ${{ secrets.PORT }}
      TF_VAR_database_name: ${{ secrets.DATABASE_NAME }}
      TF_VAR_mongodb_uri: ${{ secrets.MONGODB_URI }}
      TF_VAR_jwt_secret: ${{ secrets.JWT_SECRET }}
      TF_VAR_jwt_expires_in: ${{ secrets.JWT_EXPIRES_IN }}
      TF_VAR_jwt_token_name: ${{ secrets.JWT_TOKEN_NAME }}
      TF_VAR_salt_rounds: ${{ secrets.SALT_ROUNDS }}
      TF_VAR_service_name: ${{ secrets.SERVICE_NAME }}

      TF_VAR_docker_image: ${{ secrets.DOCKER_USERNAME }}/securebackend
      TF_VAR_docker_tag: ${{ github.sha }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve